### ISSUE TITLE
Add OpenMPI?

### ISSUE THREAD

**Issue by thomasdorch** [conda-forge/pymeep-feedstock#70]
Is it possible to add an OpenMPI-based version as well?

**Comment by oskooi** [comment]
Sorry for the delayed response. Would adding support for OpenMPI provide anything beyond what is currently available using MPICH? When we set up the Meep Conda package around 2018, it seemed the MPICH Conda packages were more up to date and better maintained than OpenMPI although the situation could have changed since then.

**Comment by thomasdorch** [comment]
The main advantage of adding the OpenMPI implementation would be to provide compatibility with other packages that use OpenMPI instead of MPICH. Other than that, though, I'm not entirely sure what the state of the two packages are. I was able to get the package to build by just adding the `openmpi` flag to the mpi options so it might be straightforward to do this now?

For context, I initially opened this because I wanted to make [this conda package](https://github.com/thomasdorch/charon-conda) (which recommends using OpenMPI) compatible with pymeep. I'm building that with MPICH now as well though so I closed this issue. 

I do still think it would be good to have both implementations for pymeep regardless though, if possible. What do you think?

**Comment by sheevy** [comment]
FYI, if you use `pymeep` via nixpkgs, you can choose your MPI privider and by default it's `OpenMPI`
